default_stages: [commit]
repos:
  - repo: local
    hooks:

      - id: ruff-format
        name: Ruff Format
        entry: ruff format
        types: [python]
        language: system

      - id: ruff-check
        name: Ruff Check
        entry: ruff check
        types: [python]
        language: system

      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        types: [python]
        language: system
